# Generated by Django 6.0.7 on 2026-08-05 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_session', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_session',
            name='day',
            field=models.CharField(max_length=60),
        ),
    ]
